from datetime import datetime
from typing import List, Dict

from app.entities.user import UserEntity
from app.interfaces.interfaces import ITaskRepository, IUserRepository
from app.entities.task import TaskEntity
from uuid import UUID
from app.exceptions.exceptions import ResponsibleTypeError, UserNotFoundError, ErrorTaskSettings


class TaskService:
    def __init__(
        self, repository: ITaskRepository, user_repository: IUserRepository
    ):
        self.repo = repository
        self.user_repo = user_repository

    # TODO CHECK ATTACHMENTS
    async def check_attachments(self, attachments: List[str]) -> Dict[str, str]:
        att_map = {}
        for attachment in attachments:
            # TODO TRY TO OPEN FILE

            att_map[attachment.split('/')[-1]] = attachment

        return att_map

    async def create(
        self,
        responsible_id: UUID,
        text: str,
        owner_id: UUID,
        attachments: List[str] = None,
        expired_at: datetime = None,
        responsible_type: str = "user",
        can_be_completed: bool = True,
        is_autogenerated: bool = False,
        autogen_id: UUID = None,
    ):
        if responsible_type == "user":
            responsible = [await self.user_repo.get_by_id(responsible_id)]
        elif responsible_type == "duty":
            responsible = await self.user_repo.get_duty_users(responsible_id)
        elif responsible_type == "project":
            responsible = await self.user_repo.get_project_users(responsible_id)
        else:
            raise ResponsibleTypeError(
                "Неверный тип ответственного за задачу. Возможные варианты: 'user', 'duty', 'project'"
            )

        if not responsible:
            raise UserNotFoundError("Ответственный не найден")

        owner = await self.user_repo.get_by_id(owner_id)
        if not owner:
            raise UserNotFoundError("Ответственный за задачу не найден")

        task = TaskEntity(
            text=text,
            owner_id=owner.id,
            expired_at=expired_at,
            can_be_completed=can_be_completed,
            status="in_progress",
            is_autogenerated=is_autogenerated,
            autogen_id=autogen_id,
            attachments=attachments,
            responsible=[UserEntity(id=u) for u in responsible]
        )

        task = await self.repo.create(task)

        att_map = await self.check_attachments(attachments)
        att_ents = []
        for key, value in att_map.items():
            att_ents.append(await self.repo.create_attachment(task_id=task.id, path=value, filename=key))
        task.attachments = att_ents
        return task
