import enum

from pydantic import BaseModel, field_validator
from typing import Optional, List
from datetime import datetime
from uuid import UUID


class TaskCreate(BaseModel):
    text: str
    attachments: Optional[List[str]] = None
    can_be_completed: Optional[bool] = True
    expired_at: Optional[datetime] = None
    is_autogenerated: Optional[bool] = False
    autogen_id: Optional[UUID] = None

    @field_validator("autogen_id")
    def check_autogen_id(cls, v, info):
        if info.get("is_autogenerated") is False and v is not None:
            raise ValueError("autogen_id must be None if is_autogenerated is False")
        elif info.get("is_autogenerated") is True and v is None:
            raise ValueError("autogen_id must be set if is_autogenerated is True")
        return v

    @field_validator("expired_at", mode="after")
    def check_date(cls, v):
        if v is None:
            return v
        v = v.replace(tzinfo=None, microsecond=0, second=0, minute=0, hour=0)
        today = datetime.today().replace(
            microsecond=0, second=0, minute=0, hour=0
        )
        if v < today:
            raise ValueError("expired_at must be today or in the future")
        return v

    @field_validator("can_be_completed")
    def check_flags(cls, v, info):
        if v and info.data.get("expired_at") is None:
            raise ValueError(
                f"expired_at must be set if {info.field_name} is True"
            )
        return v


class TaskStatus(str, enum.Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    DELETED = "deleted"


class TaskUpdate(BaseModel):
    text: str
    expected_date: Optional[datetime] = None
    attachments: Optional[List[str]] = None
    status: Optional[TaskStatus] = None

    @field_validator("expected_date", mode="after")
    def check_date(cls, v):
        if v is None:
            return v
        v = v.replace(tzinfo=None, microsecond=0, second=0, minute=0, hour=0)
        today = datetime.today().replace(
            microsecond=0, second=0, minute=0, hour=0
        )
        if v < today:
            raise ValueError("expected_date must be today or in the future")
        return v



class TaskDelete(BaseModel):
    id: UUID
